ALTER TABLE messages
  ADD COLUMN IF NOT EXISTS edited_at BIGINT,
  ADD COLUMN IF NOT EXISTS deleted BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS original_message_id TEXT;

ALTER TABLE contacts
  ADD COLUMN IF NOT EXISTS labels JSONB,
  ADD COLUMN IF NOT EXISTS lid TEXT;

ALTER TABLE whatsapp_groups
  ADD COLUMN IF NOT EXISTS invite_code TEXT,
  ADD COLUMN IF NOT EXISTS member_add_mode BOOLEAN,
  ADD COLUMN IF NOT EXISTS join_approval_mode BOOLEAN,
  ADD COLUMN IF NOT EXISTS desc_owner TEXT,
  ADD COLUMN IF NOT EXISTS subject_owner TEXT,
  ADD COLUMN IF NOT EXISTS subject_time BIGINT;